name: Build and Release Lindbergh

on:
  workflow_call:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download version.h artifact
        uses: actions/download-artifact@v4
        with:
          name: version-file
          path: src/lindbergh/

      - name: Download SDL3 libs
        uses: actions/download-artifact@v4
        with:
          name: SDL3-FAudio-ID
          path: libs/

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --target lindbergh-build -t lindbergh-loader .

      # Extract build artifacts
      - name: Extract build artifacts
        run: |
          docker create --name lindbergh-builder lindbergh-loader
          docker cp lindbergh-builder:/output ./build
          docker rm lindbergh-builder

      # Compress the build directory
      - name: Compress build directory
        run: tar -czvf build.tar.gz -C ./build .

      # Archive the build directory as an artifact for debugging
      - name: Archive build directory
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build.tar.gz

